"""empty message

Revision ID: 5aef6a0f947c
Revises: af5aad7f9b99
Create Date: 2022-05-22 19:44:32.369294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aef6a0f947c'
down_revision = 'af5aad7f9b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('created_by', sa.DateTime(), nullable=True))
    op.add_column('venue', sa.Column('created_by', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'created_by')
    op.drop_column('artist', 'created_by')
    # ### end Alembic commands ###
