"""empty message

Revision ID: 9ea3c658563b
Revises: 3ecbc3700394
Create Date: 2022-05-22 15:52:55.406268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea3c658563b'
down_revision = '3ecbc3700394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'available')
    # ### end Alembic commands ###
