"""empty message

Revision ID: af5aad7f9b99
Revises: 9ea3c658563b
Create Date: 2022-05-22 15:55:11.979898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5aad7f9b99'
down_revision = '9ea3c658563b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
